### PR TITLE
JSON5 changes and working. Will cleanup after PR

### PR DESCRIPTION
**Pull request by william8siew**
2 things to note:
1) I remove the section where if the options text does not equal the stringify then restore defaults. The reason i remove this is because stringify does not account for comments. I believe this if statement is an additional safety check so removing it shouldnt be a problem.
2) We can change the options to .json5 extensions but .json works too. I've only modified one file to be of .json5. After being approved, we can decide what to comment in all the files.

### CODE REVIEW

**Comment by Algomorph** [comment]
1. The reason I had that check there was that, for ordinary JSON, if a person would edit their options and save, the JSON would get re-ordered according to some inner ordering (with the person potentially losing their point of reference). If JSON5 accomodates for this (preserves ordering), then there should no longer be a need for that check.

2. Sounds great. I'll make a separate issue for editing the sample options. Something like that is there on the project board for the 1.0 release, I'll add these things to that issue or make a 'super-issue' out of the two of them.

Great work on this! I'll review soon.

**Review by Algomorph — CHANGES_REQUESTED** [review]
Everything mostly looks good, well done!

The modules & `submit_server_main.js` would need access to the options, which means they also need access to `third_party/json5.min.js`. Please include it in the manifest and verify that the modules load correctly.

I remember now the reason for the check & conditional restore on 112 of options.js. It was done to pretty-format the options when the user hits save. Can this be brought back?

**Comment by william8siew** [comment]
I will add `third_party/json5.min.js` to the manifest.
As for the pretty-format, I'm not sure it can format it without removing the comments. Will that be fine? If not I can try to find a way for it to achieve both but this might involve some string manipulation

**Comment by Algomorph** [comment]
I see the dilemma. I guess we cannot pretty-format it without preserving the comments unless we use something like https://github.com/rhysd/fixjson. Please proceed with removing the commented stuff / cleaning up. Could you also submit a new feature-tagged issue as a reminder to find a solution for formatting options JSON5 without removing the comments?

**Pull request merged**
