### PR TITLE
Test Module: Helper Methods are now Searched

### LINKED ISSUE #50: Test Module FP on dwei, Proj 6 (Fall 2020)
Methods "inOrderTraversal" and "rightRootLeftTraversal" get called in methods that are then called inside test methods, so they are not registered by the Test Module. This should be fixed as soon as method call chains can be properly handled.

### PR DESCRIPTION
**Pull request by msimmon6**
Resolves #50 

Basically, if a method in the tests scope begins with "this.", search the scope with this name. I had to make a recursive method for this since you can't add to a for-each loop, but this is fine.

Also, a slight modification happened in the indentation module.

### CODE REVIEW

**Review by Algomorph — CHANGES_REQUESTED** [review]
This looks as a good first approximation. However, please do separate the GUI drawing from the code searching. The code searching should be performed as the recursive function that retrieves instances of `TestedMethodCall` (make that class in the same module, it should hold all the info required to later add the stuff to `uiPanel`).

This kind of modularization is necessary in order to be able to pull off the test harness #74 & code grade categories #52.

P.S. also, please make sure to add block comments for each new function.

**Comment by msimmon6** [comment]
I was able to separate the DUI from the method. I'm unsure how I would implement with the TestedMethodCall class since I would need to update the untested methods as well, but if you fell that it's necessary feel free to request change again!

**Review by Algomorph — APPROVED** [review]
Ah, you killed two stones with one bird! Well done!

**Comment by Algomorph** [comment]
Please make sure to pull you branch locally on your machine before continuing work. I've added a small revision commit.

**Comment by msimmon6** [comment]
The revision forgot to change one line, so I will fix it with my next commit

**Comment by Algomorph** [comment]
Sorry about that. Thanks for the fix! Feel free to directly merge into master, no need for a PR for a one-liner fix.

**Comment by msimmon6** [comment]
Done! I also accidentally included something else (now static methods incorrectly tested as non-static may be picked up), but it is a feature.

**Pull request merged**
